; Dunedin AI - Magrathea config

[general]
	use_environment = "dev"
	time_zone = "America/Sao_Paulo"

[dev]
	db_host = "$=DB_HOST"
	db_name = "$=DB_NAME"
	db_user = "$=DB_USER"
	db_pass = "$=DB_PASSWORD"
	time_zone = "America/Sao_Paulo"
	logs_path = "/var/www/html/logs"
	cache_path = "/var/www/html/cache"
	app_url = "http://localhost:3000"
	no_cache = true
	firebase_id = "$=FIREBASE_PROJECT_ID"

[prod]
	db_host = "$=DB_HOST"
	db_name = "$=DB_NAME"
	db_user = "$=DB_USER"
	db_pass = "$=DB_PASSWORD"
	time_zone = "America/Sao_Paulo"
	logs_path = "/var/www/html/logs"
	cache_path = "/var/www/html/cache"
	app_url = "httpss://www.project.app"
	no_cache = true
	firebase_id = "$=FIREBASE_PROJECT_ID"
